#!/usr/bin/env python3
import asyncio
import sys
import uuid
from datetime import datetime, timezone
from sqlmodel import select

from apiapp.core.config import get_settings
from apiapp.infrastructure.database import init_db, db_client
from apiapp.modules.user.model import User
from apiapp.modules.user.schemas import UserRole


async def create_user_admin():
    from dotenv import load_dotenv
    from pathlib import Path
    import os

    project_root = Path(__file__).resolve().parent.parent
    env_file = (
        ".env"
        if os.getenv("APP_ENV") == "dev"
        else ".env.prod"
        if os.getenv("APP_ENV") == "prod"
        else ".env.test"
    )
    env_path = project_root / env_file
    if not env_path.exists():
        env_path = project_root / ".env"
    load_dotenv(env_path)

    settings = get_settings()
    
    # Initialize DB (which gathers models and runs create_all)
    await init_db(settings)

    print("start check admin")
    async with db_client.session_maker() as session:
        statement = select(User).where(User.username == "admin")
        result = await session.exec(statement)
        user = result.first()

        if user:
            print("Found admin user", user)
            await db_client.close()
            return
        
        print("end check admin")

        print("start create admin")
        user = User(
            id=uuid.uuid4(),
            email="admin@example.com",
            username="admin",
            hashed_password="",
            name="admin system",
            role=UserRole.ADMIN,
            is_active=True,
            created_at=datetime.now(timezone.utc),
        )
        print(user.email)
        user.set_password("p@ssw0rd")
        session.add(user)
        await session.commit()
        await session.refresh(user)
        print("finish")
        
    await db_client.close()


if __name__ == "__main__":
    asyncio.run(create_user_admin())
